---
title: "Malformation Analysis"
author: "Ryan Taylor"
format: 
  html:
    embed-resources: true
    theme: paper
    highlight: haddock
    code-fold: true
    toc: true
    toc-location: left
    code-overflow: wrap
    df-print: kable
    knitr:
      opts_chunk:
        echo: true
        include: true
        message: false
        warning: false
        results: markup
        fig.align: center
        fig.height: 5
        fig.width: 7
        fig.path: "../results/2026 ENAR Figures/"
        R.options:
          scipen: 999
          knitr.kable.NA: ""
number-sections: true
editor: source
---

::: {.hidden}
$$
\usepackage{xcolor}

\newcommand{\bX}{\mathbf X}
\newcommand{\bY}{\mathbf Y}
\newcommand{\by}{\mathbf y}
\newcommand{\bH}{\mathbf H}
\newcommand{\bh}{\mathbf h}
\newcommand{\bx}{\mathbf x}
\newcommand{\bG}{\mathbf G}
\newcommand{\bg}{\mathbf g}
\newcommand{\bS}{\mathbf S}
\newcommand{\bs}{\mathbf s}
\newcommand{\bP}{\mathbf P}
\newcommand{\bC}{\mathbf C}
\newcommand{\bI}{\mathbf I}
\newcommand{\hatbG}{\widehat \bG}
\newcommand{\ba}{\mathbf a}
\newcommand{\bz}{\mathbf z}
\newcommand{\bb}{\mathbf b}
\newcommand{\bB}{\mathbf B}
\newcommand{\bw}{\mathbf w}
\newcommand{\bW}{\mathbf W}
\newcommand{\bZ}{\mathbf Z}
\newcommand{\bV}{\mathbf V}
\newcommand{\bU}{\mathbf U}

\newcommand{\balpha}{\boldsymbol{\alpha}}
\newcommand{\bbeta}{\boldsymbol{\beta}}
\newcommand{\bgamma}{\boldsymbol{\gamma}}
\newcommand{\bepsilon}{\boldsymbol{\epsilon}}
\newcommand{\bphi}{\boldsymbol{\phi}}
\newcommand{\hatbbeta}{\hat{\bbeta}}
\newcommand{\hatbgamma}{\hat{\bgamma}}
\newcommand{\bSigma}{\boldsymbol{\Sigma}}
\newcommand{\bsigma}{\boldsymbol{\sigma}}
\newcommand{\hatVar}{\widehat{\Var}}
\newcommand{\hatCov}{\widehat{\Cov}}
\newcommand{\bLambda}{\boldsymbol{\Lambda}}
\newcommand{\hatbLambda}{\hat{\bLambda}}
\newcommand{\blambda}{\boldsymbol{\lambda}}
\newcommand{\hatblambda}{\hat{\blambda}}
\newcommand{\btheta}{\boldsymbol{\theta}}
\newcommand{\hatbSigma}{\widehat{\boldsymbol{\Sigma}}}
\newcommand{\bmu}{\boldsymbol{\mu}}
\newcommand{\bzeta}{\boldsymbol{\zeta}}
\newcommand{\bomega}{\boldsymbol{\omega}}
\newcommand{\bOmega}{\boldsymbol{\Omega}}

\newcommand{\diag}{\mathrm{diag}}
\newcommand{\tr}{\mathrm{tr}}

\newcommand{\bzero}{\boldsymbol{0}}
\newcommand{\bone}{\boldsymbol{1}}
\def\iid{\,{\buildrel iid \over \sim}\,} 
\newcommand{\reals}{\mathbb{R}}
$$
:::

```{r}
#| label: setup
#| include: false

# Clear memory
rm(list = ls()); gc(verbose = F)

# Load packages
# if(!require("pacman")) install.packages("pacman")
pacman::p_load(
  # Specialty
  itsadug, spdep, concaveman, sf,
  
  # Bayes
  mvtnorm, coda,
  
  # Format
  latex2exp, table1, gtsummary,
  broom.helpers, broom.mixed, colorspace, gtsummary,
  
  # Modeling
  mgcv,
  
  # Useful extensions
  gtools, readxl, data.table, reshape2, ggridges, Matrix, MASS, ggh4x, gamair,
  
  # Basics
  DescTools, tidyverse, magrittr, janitor, glue, skimr,
  knitr, kableExtra, ggpubr, ggpmisc, here
)

# # Load my Rcpp functions
# library(DevCranio)

# Load my R functions
source(here("source", "load_matrix_data_fn.R"))
source(here("source", "obtain_predictions_fn.R"))
source(here("source", "lm_penalized_gibbs_fn.R"))
source(here("source", "construct_smooth_ref_code_fns.R"))
source(here("source", "hierarchical_penalized_gibbs_fn.R"))
source(here("source", "simulate_data_fn.R"))
source(here("source", "mv_normal_matrix_fn.R"))

```

# Load data

```{r}
#| label: data

sim_date <- "2026-04-07"
model_date <- "2026-04-21"

# Load image-level data
cranio_sub <- readRDS(file = here::here("analysis", "intermediate",
                                        "demographics_filtered.rds"))

# Load dataset of matrices and demographics after filtering down
cranio_matrix <- readRDS(file = here::here("analysis", "intermediate", 
                                           "covars_and_matrices_sub.rds"))

# Load region-level models
region_models <- readRDS(
    file = here::here("analysis", "intermediate",
                      "prelim_models_region.rds"))

# Load pixel-level model summaries
load(file = here::here("analysis", "intermediate",
                       "prelim_model_pixels_summ.rda"))

# Load 2-D GAM tensor models
fusion_models <- readRDS(
    file = here::here("analysis", "intermediate", "prelim_models_fusion_te.rds"))

# Load soap film object
load(file = here::here("analysis", "intermediate", "soap_object.rda"))

## Load most recent simulation results

# Load individuals we're fitting simulations on (demo_test_df)
load(file = here::here("analysis", "intermediate",
                         paste0("simulation_demographics.rda")))

# Output from the most recent Gibbs sampler (hierarchy_test)
load(file = here::here("analysis", "intermediate",
                       paste0("hierachical_test_",
                              sim_date, 
                              ".rda")))

# True values from the same day (demo_effect_Mx, gamma_true)
load(file = here::here("analysis", "intermediate",
                       paste0("hierachical_test_true_vals_",
                              sim_date, 
                              ".rda")))

# Load joint model run (cranio_joint)
load(file = here::here("analysis", "intermediate", 
                       paste0("joint_model_fit_",
                       model_date,
                       ".rda")))

# Load region object (matrix_region)
load(file = here::here("analysis", "intermediate", "region_shape_object.rda"))

# Load covariates components of data (cranio_coeff_ingredients)
load(file = here::here("analysis", "intermediate", "demographics_model_matrices.rda"))

```

```{r}
#| label: constants

# Set maximum age as 3 years old
cranio_max_age <- 365

# Set age categories
cranio_age_breaks <- c(seq(0, 300, 60), cranio_max_age)

# Label these with spaces so they can wrap in plots
cranio_age_break_labels <- map_chr(2:length(cranio_age_breaks),
                            ~paste0(cranio_age_breaks[.-1],
                                    " - ",
                                    if_else(. == length(cranio_age_breaks), "", "<"),
                                    cranio_age_breaks[.]))

# Set consistent colors for every time fusions pop up
fusion_color_dict <- distinct(cranio_sub, fusion_type) %>%
  arrange(fusion_type) %>%
  mutate(color = palette.colors(palette = "Set1")[c(1:5, 7)])
```


# Introduction

## Table 1

```{r}
#| label: table1

cranio_sub %<>%
  mutate(sex_name = fct_recode(sex, "Female" = "0", "Male" = "1"))

t1 <- tbl_summary(cranio_sub, 
                  include = c(age, sex_name), 
                  by = fusion_type,
                  label = list(
                    age ~ "Age (Days)",
                    sex_name ~ "Sex"
                  ),
                  type = list(
                    all_continuous() ~ "continuous2"),
                  statistic = list(
                    all_continuous() ~ c(
                    "{median} ({p25}, {p75})",
                    "{mean}"
                  ))) %>% 
  modify_header(all_stat_cols() ~ "**{level}**  \nN = {n} ({style_percent(p)}%)") %>% 
  add_overall() %>% 
  remove_footnote_header()

t1_p <- t1 %>% 
  as_kable_extra(booktabs = T, format = "latex")
```

## Average by fusion

```{r}
#| label: normative shape

# Create dataset of average cell for each fusion
matrix_fusion <- cranio_matrix %>%
  # Extract only fusion type and outcome from nested data
  hoist(data, "fusion_type", "diff") %>%
  select(-c(data, region)) %>%
  unnest_longer(col = c(fusion_type, diff)) %>%
  # Summarize average by pixel and fusion type
  group_by(row, col, fusion_type) %>%
  summarize(diff_avg = mean(diff)) %>%
  ungroup()

plot_fusion <- ggplot(matrix_fusion %>% 
                        filter(fusion_type == "Normative")) +
  geom_raster(aes(x = row, y = col, fill = diff_avg)) +
  coord_fixed() +
  theme_void() +
  scale_fill_viridis_c(option = "turbo") +
  labs(fill = "Avg. Growth") +
  theme(legend.position = "bottom")

ggsave("../results/2026 ENAR Figures/fusion_norm_average.png",
       plot_fusion,
       height = 8, width = 5, units = "in")
```

## Average by fusion and age bins

```{r}
#| label: fusion age

# Summarize by age, region, and fusion type; have option to round to nearest month
# Create dataset with fusion and age info
matrix_age_fusion <- cranio_matrix %>%
  hoist(data, "fusion_type", "age", "diff") %>%
  select(-c(data, region)) %>%
  unnest_longer(col = c(fusion_type, age, diff)) %>%
  # Add age categories
  mutate(age_bin = cut(age,
                       breaks = cranio_age_breaks,
                       labels = cranio_age_break_labels,
                       right = FALSE, include.lowest = T)) %>%
  # Summarize average in these bins
  group_by(row, col, fusion_type, age_bin) %>%
  summarize(diff_avg = mean(diff)) %>%
  ungroup() %>% 
  # Add binned age label
  mutate(age_bin_header = "Age (Days)")

# Plot brain map by fusion type and age
plot_fusion_age <- ggplot(matrix_age_fusion %>% 
                            filter(fusion_type %in% c("Normative", "Sagittal"))) +
  geom_raster(aes(x = row, y = col, fill = diff_avg)) +
  facet_nested(fusion_type ~ age_bin_header + age_bin,
               labeller = label_wrap_gen(),
               nest_line = element_line(linetype = 3),
               resect = unit(0.2, "cm")) +
  coord_fixed() +
  scale_fill_viridis_c(option = "turbo") +
  theme_void() +
  theme(axis.text = element_blank(),
        axis.ticks = element_blank()) +
  labs(fill = "Avg. Growth") +
  theme(legend.position = "bottom",
        strip.text.x = element_text(size = 10, 
                                    margin = margin(t = 2, b = 3)))

ggsave("../results/2026 ENAR Figures/fusion_age_average.png",
       plot_fusion_age,
       height = 3, width = 6, units = "in")
```

# Methods

## Fit tensor product models

```{r}
#| label: 2d gam

# Create polygon around pixels in cranium shape
cranio_bound_shape <- cranio_matrix %>%
  distinct(row, col) %>%
  st_as_sf(coords = c("row", "col")) %>%
  concaveman(concavity = 1)

# Create boundary as points
cranio_bound_matrix <- cranio_bound_shape %>%
  # Add buffer so boundary is beyond data
  st_buffer(1) %>%
  # Convert to line
  st_boundary() %>%
  # Take points along this line at density = 1 unit
  st_line_sample(density = 1) %>%
  st_coordinates() %>%
  as_tibble() %>%
  rename(row = X, col = Y) %>%
  # Add order of appearance in data
  mutate(appearance_order = 1:n())

# Set new data for GAM
newdata_fusiongam <- tibble(
  fused_Sagittal = 0,
  fused_Metopic = 0,
  fused_RCoronal = 0,
  fused_LCoronal = 0,
  sex = 0,
  age = 300,
  row = list(seq(from = (min(cranio_bound_matrix$row) - 10),
                 to = (max(cranio_bound_matrix$row) + 10),
                 length.out = 50)),
  col = list(seq(from = (min(cranio_bound_matrix$col) - 10),
                 to = (max(cranio_bound_matrix$col) + 10),
                 length.out = 50))
) %>%
  unnest_longer(row) %>% unnest_longer(col)

fusion_models  %<>%
  # Predict from this model for spatial pattern (1 year old male)
  mutate(pred_data = map(
    model,
    ~obtain_predictions(.x, newdata = newdata_fusiongam)))

# Summarize 2-D model predictions
fusion_model_summ <- fusion_models %>%
  select(fusion_type, pred_data) %>%
  unnest(pred_data)

# Plot these predictions (in a rectangle shape with brain mask)
plot_model_fusion <- ggplot() +
  geom_raster(data = fusion_model_summ,
              aes(x = row, y = col, fill = fit)) +
  geom_sf(data = cranio_bound_shape, fill = NA, linewidth = 1) +
  facet_wrap(~fusion_type, nrow = 1) +
  scale_fill_viridis_c(option = "turbo",
                       limits = quantile(fusion_model_summ$fit, 
                                         c(0.01, 0.99))) +
  theme_void() +
  theme(axis.text = element_blank(),
        axis.ticks = element_blank()) +
  labs(fill = "Pred. Growth\n(10 mo. F)") +
  theme(legend.position = "bottom")

plot_model_fusion

ggsave("../results/2026 ENAR Figures/fusion_tensors.png",
       plot_model_fusion,
       height = 2, width = 6, units = "in")
```

## Plot soap film basis functions

```{r}
#| label: plot basis functions

so_GRID_N <- 10

# Identify row knot points
grid_row <- seq(min(cranio_bound_matrix$row), max(cranio_bound_matrix$row),
                length.out = so_GRID_N)

# Identify column knot points
grid_col <- seq(min(cranio_bound_matrix$col), max(cranio_bound_matrix$col),
                length.out = so_GRID_N)

# Expand to grid of knots
grid_all <- expand.grid("row" = grid_row, "col" = grid_col)

# Crop to cranial boundary
so_grid_k <- grid_all %>%
  st_as_sf(coords = c("row", "col")) %>%
  st_filter(cranio_bound_shape) %>%
  st_coordinates() %>%
  as_tibble() %>%
  rename(row = X, col = Y)

# Keep only points that we need to build smoother
so_matrix_pts <- cranio_matrix %>%
  select(row, col)

# Add in distances determined in smoother object
bound_points <- cranio_bound_matrix %>%
  mutate(bound_r = cranio_soap$sd$bnd[[1]]$d[-1]) %>%
  st_as_sf(coords = c("row", "col"), remove = F)

# Convert points within matrix to sf for nearest neighbor
matrix_sf <- so_matrix_pts %>% st_as_sf(coords = c("row", "col"), remove = F)

# Identify nearest matrix neighbor to each boundary point
bound_points %<>%
  mutate(nearest_cell = st_nearest_feature(bound_points, matrix_sf)) %>%
  st_drop_geometry() %>%
  select(nearest_cell, bound_r)

# Match matrix points to their order on the boundary
matrix_pts_df <- so_matrix_pts %>%
  mutate(cell_id = 1:n()) %>%
  left_join(bound_points,
            by = c("cell_id" = "nearest_cell")) %>%
  # When we get multiple matches, take first point on boundary
  arrange(cell_id, bound_r) %>%
  group_by(cell_id) %>%
  slice(1) %>%
  ungroup() %>%
  select(-cell_id)

# Identify different parts of penalty matrix
cols_bound <- which(apply(cranio_soap$S[[1]], 2, function(x) sum(x != 0)) != 0)
cols_film <- which(apply(cranio_soap$S[[2]], 2, function(x) sum(x != 0)) != 0)

# Create data of basis functions and pixel locations for plotting
basis_df <- cranio_soap$X %>%
  data.frame() %>%
  bind_cols(matrix_pts_df) %>%
  pivot_longer(-c(row, col, bound_r),
               names_to = "basis_fn") %>%
  mutate(basis_fn = as.numeric(str_remove(basis_fn, "X")),
         fn_cat = case_when(basis_fn %in% cols_bound ~ "Boundary",
                            basis_fn %in% cols_film ~ "Interior"))

# Link knots to interior basis functions
so_grid_k %<>% mutate(basis_fn = cols_film)

# Plot boundary cyclic 1-dimensional splines
soap_basis_cyclic <- ggplot(data = basis_df %>%
                              filter(!is.na(bound_r) & fn_cat == "Boundary")) +
  geom_line(aes(x = bound_r, y = value, color = factor(basis_fn))) +
  scale_color_brewer(palette = "Paired") +
  labs(x = "Distance Along Boundary",
       y = "Function Value",
       color = "Basis Fn.") +
  theme_minimal() +
  theme(legend.position = "bottom") +
  guides(color = guide_legend(nrow = 1, byrow = T))

ggsave("../results/2026 ENAR Figures/basis_cyclic.png",
       soap_basis_cyclic,
       height = 2, width = 6, units = "in")

# Plot boundary-induced 2-dimensional basis functions
soap_basis_bd <- ggplot() +
  geom_raster(data = basis_df %>% filter(fn_cat == "Boundary"),
              aes(x = row, y = col, fill = value)) +
  scale_fill_viridis_c() +
  labs(x = NULL, y = NULL, fill = "Fn. Value") +
  coord_fixed() +
  theme_void() +
  theme(legend.position = "bottom") +
  facet_wrap(~basis_fn, nrow = 1)

ggsave("../results/2026 ENAR Figures/basis_boundary.png",
       soap_basis_bd,
       height = 2, width = 8, units = "in")

# Plot interior basis functions with corresponding knots
soap_basis_int <- ggplot() +
  geom_raster(data = basis_df %>% filter(basis_fn %in% c(10:12, 38:40, 67:69)),
              aes(x = row, y = col, fill = value)) +
  geom_point(data = so_grid_k %>% select(-basis_fn),
             aes(x = row, y = col),
             color ="black", size = 0.01) +
  geom_point(data = so_grid_k %>% filter(basis_fn %in% c(10, 39, 69)),
             aes(x = row, y = col),
             color ="red", size = 0.01) +
  scale_fill_viridis_c() +
  labs(x = NULL, y = NULL, fill = "Fn. Value") +
  coord_fixed() +
  theme_void() +
  theme(legend.position = "bottom") +
  facet_wrap(~basis_fn, nrow = 1)

ggsave("../results/2026 ENAR Figures/basis_interior.png",
       soap_basis_int,
       height = 2, width = 8, units = "in")
```

## Plot Aral Sea example

```{r}
#| label: aral-example

# Load aral sea chloropyll data
data(aral); data(aral.bnd)

# Convert to spatial for easier plotting
aral_bound <- aral.bnd %>% 
  as.data.frame() %>% 
  st_as_sf(coords = c("lon", "lat"), remove = F)

aral_bound <- bind_rows(aral_bound, slice(aral_bound, 1)) %>% 
  st_combine() %>% 
  st_cast("POLYGON")

aral_sf <- aral %>% 
  st_as_sf(coords = c("lon", "lat"), remove = F)

# Plot data
aral_data_plot <- ggplot() +
  geom_sf(data = aral_bound, fill = NA) +
  geom_sf(data = aral_sf, aes(color = chl)) +
  scale_color_viridis_c() +
  labs(x = NULL, y = NULL, color = "Chlorophyll") +
  theme_minimal() +
  theme(legend.position = "bottom")

# Make knots
knot_axis_num <- 5

aral_grid <- expand.grid(
  "lon" = seq(min(aral$lon), max(aral$lon), length.out = knot_axis_num),
  "lat" = seq(min(aral$lat), max(aral$lat), length.out = knot_axis_num)
)

aral_grid_all <- aral_grid %>%
  st_as_sf(coords = c("lon", "lat"))

# Crop to cranial boundary
aral_grid_knots <- aral_grid %>%
  st_as_sf(coords = c("lon", "lat")) %>%
  st_filter(st_buffer(aral_bound, -0.01), .predicate = st_covered_by)

aral_k <- aral_grid_knots %>% 
  st_coordinates() %>%
  as_tibble() %>%
  rename(lon = X, lat = Y)

# Fit soap film
aral_soap <- gam(chl ~ s(lon, lat, 
                         k=30,
                         bs = "so",
                         xt = list(bnd = list(aral.bnd))),
                         knots = aral_k, data = aral)

# Predict on regular grid

new_aral <- st_make_grid(aral_bound, 
                         n = 200,
                         what = "centers") %>% 
  as_tibble() %>% 
  st_as_sf() %>% 
  mutate(lon = st_coordinates(geometry)[,1],
         lat = st_coordinates(geometry)[,2])

new_aral %<>% mutate(pred = predict(aral_soap, new_aral))

aral_preds <- ggplot() +
  geom_sf(data = new_aral, aes(color = pred)) +
  scale_color_viridis_c() +
  labs(x = NULL, y = NULL, color = "Pred. Chlorophyll") +
  theme_void() +
  theme(legend.position = "bottom")

ggsave("../results/2026 ENAR Figures/aral_predictions.png",
       aral_preds,
       height = 5, width = 6, units = "in")

```


# Results

## Load simulation results

```{r}
#| label: simulation object

# Identify sample of gammas to plot
gammas_to_check <- c(1:2, 6:7, 48:49, 64:65)
```

## Visualize beta curves

```{r}
#| label: beta effect curves

# Calculate true gammas across age
beta_curve_true <- demo_new_design %*% demo_effect_mx

beta_curve_df <- beta_curve_true %>% 
  as.matrix() %>% 
  as.data.frame() %>% 
  mutate(subject = 1:n()) %>% 
  bind_cols(demo_newdata) %>% 
  pivot_longer(matches("V"), names_to = "Gamma") %>% 
  mutate(Gamma = as.numeric(str_remove(Gamma, "V")))

# Extract posterior mean estimates
beta_post <- apply(hierarchy_test$beta, c(1,2), mean)

beta_curve_est <- demo_new_design %*% beta_post

beta_curve_est_df <- beta_curve_est %>% 
  as.matrix() %>% 
  as.data.frame() %>% 
  mutate(subject = 1:n()) %>% 
  pivot_longer(matches("V"), names_to = "Gamma", values_to = "estimate") %>%
  mutate(Gamma = as.numeric(str_remove(Gamma, "V"))) %>% 
  left_join(beta_curve_df %>% rename(coefficient = value)) %>% 
  pivot_longer(c(estimate, coefficient), names_to = "value_type") %>% 
  mutate(value_type = case_match(value_type, 
                                 "coefficient" ~ "True",
                                 "estimate" ~ "Est."))

beta_curve_est_plot <- ggplot(beta_curve_est_df %>% 
                           filter(Gamma %in% gammas_to_check &
                                    str_detect(fusion_type, "Only|Norm")),
                         aes(x = age, y = value, 
                             color = fusion_type, linetype = value_type)) +
  geom_line() +
  facet_wrap(~Gamma, labeller = label_both, scales = "free_y", nrow = 2) +
  scale_linetype_manual(values = c("True" = 1,
                                   "Est." = 5)) +
  theme_minimal() +
  theme(legend.position = "bottom",
        legend.box = "vertical",
        axis.text.x = element_text(angle = 45, hjust = 1)) +
  labs(x = "Age", y = "Gamma Value",
       linetype = "Type", color = "Fusion")

beta_curve_est_plot

ggsave("../results/2026 ENAR Figures/beta_curves_simulated.png",
       beta_curve_est_plot,
       height = 4, width = 6, units = "in")
```

## Check gamma coefficients

```{r}
#| label: gamma scatter


# Take posterior mean of gammas
gamma_post <- apply(hierarchy_test$gamma, c(1,2), mean)

# Turn into DF and merge with true values
gamma_vals <- reshape2::melt(gamma_post) %>% 
  left_join(reshape2::melt(as.matrix(gamma_true), value.name = "true")) %>% 
  rename(row = Var1, col = Var2) %>% 
  left_join(demo_test_df %>% mutate(row = 1:n())) %>% 
  mutate(soap_cat = if_else(col <= 9, "Boundary", "Interior"))

# Plot gamma estimates against true values
gamma_scatter <- ggplot(gamma_vals, 
                        aes(x = true, 
                            y = value, 
                            color = fusion_type,
                            shape = soap_cat)) +
  geom_point(alpha = 0.25) +
  ggpubr::stat_cor(aes(label = after_stat(rr.label)),
                   r.digits = 2,
                   label.x.npc = 0, label.y.npc = 1) +
  scale_shape_manual(values = c("Boundary" = 17,
                                "Interior" = 16)) +
  facet_grid(fusion_type~soap_cat, scales = "free") +
  theme_minimal() +
  theme(legend.position = "bottom", 
        legend.box = "vertical") +
  labs(x = "True Value", y = "Estimate",
       color = "Fusion", shape = "Soap Film Basis")

gamma_scatter

ggsave("../results/2026 ENAR Figures/gamma_simulated.png",
       gamma_scatter,
       height = 5, width = 6, units = "in")

```

## Actual Data Visualization

```{r}
#| label: load real data objects

# Find nearest point in image data to each region's centroid
mx_pt_shape <- st_as_sf(so_matrix_pts, coords = c("row", "col"))

sample_points <- st_nearest_feature(matrix_region$centroid, mx_pt_shape)

# Plot points on the shape
plot_sample <- ggplot() +
  geom_sf(data = matrix_region) +
  geom_sf(data = mx_pt_shape[sample_points,], color = "red") +
  geom_sf_text(data = matrix_region %>% st_drop_geometry(), 
               aes(label = region, geometry = centroid),
               nudge_x = -10, nudge_y = 10) +
  theme_void()

ggsave("../results/2026 ENAR Figures/sample_point_plots.png",
       plot_sample,
       height = 5, width = 3, units = "in")
```

```{r}
#| label: plot joint model patterns

## Generate sample data
joint_newdata <- cranio_sub %>%
  mutate(min_age = min(age),
         max_age = max(age)) %>%
  distinct(fusion_type, min_age, max_age) %>%
  rowwise() %>%
  mutate(age = list(seq(min_age, max_age, by = 10))) %>%
  ungroup() %>%
  select(-c(min_age, max_age)) %>%
  mutate(sex = 0) %>%
  unnest(age) %>%
  mutate(sex = factor(sex, levels = levels(cranio_sub$sex)),
         fusion_type = factor(fusion_type, levels = levels(cranio_sub$fusion_type)))

# Convert sample data to design matrix
# Create predictions by fusion type
joint_new_X_list <- map(cranio_coeff_ingredients$smooth,
                        ~PredictMat(.x, data = joint_newdata))

# Combine to create Normative and add unpenalized terms
joint_new_design <- Reduce(
  "cbind", c(
    list(
      model.matrix(~sex + fusion_type, data = joint_newdata),
      Reduce("+", joint_new_X_list)),
    joint_new_X_list[-1]
  ))

## Calculate estimated gammas for this sample data from posterior betas
joint_new_gammas <- apply(cranio_joint$beta, 3,
                          function(x){ joint_new_design %*% x}, simplify = F)

## Calculate estimated outcomes from these estimated gammas

# Extract the design matrix for the sample points we've identified
basis_sample <- cranio_soap$X[sample_points,]

# Calculate estimated outcomes for each set of estimated gammas
joint_outcomes_new <- simplify2array(
  map(joint_new_gammas, ~tcrossprod(.x, basis_sample)))

# Take mean and 95% credible interval(?) from these estimates
joint_outcomes_est <- apply(joint_outcomes_new, c(1, 2),
                            FUN = function(x) matrix(
                              c(mean(x),
                                quantile(x, 0.05),
                                quantile(x, 0.95)),
                              nrow = 1
                            ))

# Reshape estimates
joint_outcomes_df <- joint_outcomes_est %>%
  reshape2::melt() %>%
  rename(metric = Var1,
         row_num = Var2,
         region_num = Var3,
         estimate = value) %>%
  mutate(metric = case_match(metric,
                             1 ~ "mean",
                             2 ~ "pct05",
                             3 ~ "pct95"))

# Merge to interpretable data
joint_newdata_est <- joint_newdata %>%
  mutate(row_num = 1:n()) %>%
  left_join(joint_outcomes_df)

# Add scale for alpha
fusion_color_dict %<>%
  mutate(alpha = if_else(fusion_type == "Normative", 1, 0.5))

# Create plots of mean predictions
joint_estimates_plot <- ggplot(joint_newdata_est %>%
                                 filter(metric == "mean" &
                                          !str_detect(fusion_type, "oronal")),
                               aes(x = age, y = estimate,
                                   color = fusion_type)) +
  geom_line() +
  facet_wrap(~factor(region_num, 
                     levels = c(1:4, 12, 11, 6, 5, 10, 9, 8, 7)),
             ncol = 4, scales = "free_y") +
  scale_color_manual(values = fusion_color_dict %>%
                       select(fusion_type, color) %>%
                       deframe()) +
  theme_minimal() +
  theme(legend.position = "bottom") +
  labs(x = "Age (Days)",
       y = "Estimated Growth",
       color = "Fusion Type")

ggsave("../results/2026 ENAR Figures/joint_regional_paths.png",
       joint_estimates_plot,
       height = 6, width = 8, units = "in")
```

```{r}
#| label: create plots of full surface expansion

# Filter to a subset of sample individuals at interpretable ages
joint_surface_data <- joint_newdata %>% 
  mutate(row_num = row_number()) %>% 
  filter(age %in% seq(30, 330, 60))

# Extract gammas specific to these individuals
joint_surface_gammas <- map(joint_new_gammas,
                            function(x) x[joint_surface_data$row_num,])

joint_gammas_surface_mean <- Reduce("+", joint_surface_gammas) / length(joint_surface_gammas)

# Calculate estimated outcomes for each set of estimated gammas
joint_outcomes_surface <- tcrossprod(joint_gammas_surface_mean, cranio_soap$X)

# Convert to DF and merge in relevant info
joint_outcomes_surface_df <- reshape2::melt(joint_outcomes_surface) %>% 
  rename(row_num = Var1, cell_num = Var2) %>% 
  left_join(joint_surface_data) %>% 
  left_join(so_matrix_pts %>% mutate(cell_num = row_number())) %>% 
  mutate(age_header = "Age (Days)")

# Plot outcomes by suture fusion and age
outcomes_plot_sag_met <- ggplot(joint_outcomes_surface_df %>% 
                            filter(fusion_type %in% c("Normative", "Sagittal", "Metopic"))) +
  geom_raster(aes(x = row, y = col, fill = value)) +
  facet_nested(fusion_type ~ age_header + age,
               nest_line = element_line(linetype = 3)) +
  coord_fixed() +
  scale_fill_viridis_c(option = "turbo") +
  theme_void() +
  theme(axis.text = element_blank(),
        axis.ticks = element_blank()) +
  labs(fill = "Est. Growth") +
  theme(legend.position = "bottom",
        strip.text.x = element_text(size = 10, 
                                    margin = margin(t = 2, b = 3)))

outcomes_plot_sag_met

outcomes_plot <- ggplot(joint_outcomes_surface_df) +
  geom_raster(aes(x = row, y = col, fill = value)) +
  facet_nested(fusion_type ~ age_header + age,
               nest_line = element_line(linetype = 3)) +
  coord_fixed() +
  scale_fill_viridis_c(option = "turbo") +
  theme_void() +
  theme(axis.text = element_blank(),
        axis.ticks = element_blank()) +
  labs(fill = "Est. Growth") +
  theme(legend.position = "bottom",
        strip.text.x = element_text(size = 10, 
                                    margin = margin(t = 2, b = 3)))

ggsave("../results/2026 ENAR Figures/joint_sag_met_surface.png",
       outcomes_plot_sag_met,
       height = 4, width = 6, units = "in")

```

## Diagnostics

```{r}
#| label: diagnostics

# Check timing
joint_time <- cranio_joint$timing %>%
  mutate(pct = as.numeric(secs) / last(secs)) %>%
  arrange(desc(pct))

# Extract values by iteration for trace plots
# Turn parameters into long table for trace plotting
joint_gibbs_tr <- imap(
  # Remove timing from output
  cranio_joint %>%
    list_modify("timing" = zap(),
                "start-stop" = zap()),
  function(x, xn){

    x_dim <- length(dim(x))

    # Turn array into long format
    x <- reshape2::melt(x) %>% mutate(param_cat = xn)

    # Rename to identify iterations and parameter numbers
    if(x_dim == 2){

      x <- rename(x, param_num = Var1, iter = Var2)

    } else if (x_dim == 3){

      x <- rename(x, row_num = Var1, col_num = Var2, iter = Var3)

    }

    x
  }
) %>%
  # Combine
  list_rbind() %>%
  # Create ID for parameters to be identified
  group_by(param_cat) %>%
  mutate(row_id = str_pad(row_num,
                          ceiling(log10(max(row_num))),
                          "left", "0"),
         col_id = str_pad(col_num,
                          ceiling(log10(max(col_num))),
                          "left", "0"),
         param1_id = str_pad(param_num,
                             ceiling(log10(max(param_num))),
                             "left", "0"),
         is_scalar = if_else(!is.na(max(param_num)) & max(param_num) == 1,
                             1, 0)) %>%
  ungroup() %>%
  # Identify each unique parameter by row and column or by index in matrix
  mutate(param_id = if_else(is.na(param_num),
                            paste0(row_id, "_", col_id),
                            param1_id)) %>%
  select(-c(row_id, col_id, param1_id)) %>%
  # Identify burn-in vs. posterior distribution
  mutate(draw_cat = if_else(str_detect(param_cat, "burn"),
                            "Burn-In", "Post-Burn"),
         param_clean = str_remove(param_cat, "burn_")) %>%
  mutate(parameter = if_else(is_scalar == 1, param_clean,
                             paste0(param_clean, "_", param_id))) %>%
  select(-is_scalar)

# Compute effective sizes
joint_gibbs_effn <- map(
  cranio_joint[c("sigma_sq", "tau_sq",
                 "lambda_basis", "lambda_demo")],
  ~apply(., 1, effectiveSize)) %>% 
  enframe() %>% 
  unnest_longer(value) %>% 
  mutate(name = case_when(
    name == "lambda_basis" & 
      lead(name, 1) ==  "lambda_basis" ~ "lambda_c",
    name == "lambda_basis" ~ "lambda_w",
    name == "lambda_demo" ~ "lambda_alpha",
    T ~ name)) %>% 
  rename(eff_n = value,
         parameter = name)

# Add to other data

joint_gibbs_tr %<>%
  mutate(parameter = case_when(
    parameter == "lambda_basis_1" ~ "lambda_c",
    parameter == "lambda_basis_2" ~ "lambda_w",
    parameter == "lambda_demo" ~ "lambda_alpha",
    T ~ parameter
  )) %>% 
  left_join(joint_gibbs_effn)

# Trace plot of sigma
basis_trace_joint <- ggplot(joint_gibbs_tr %>%
                             filter(str_detect(parameter, "sigma_sq|lambda_c|lambda_w")),
                            aes(x = iter, y = value)) +
  geom_line() +
  facet_wrap(~interaction(draw_cat, parameter),
             ncol = 2, scales = "free") +
  theme_minimal() +
  labs(title = "Soap Film Variance Traces",
       x = "Iteration", y = "Value")

# Trace plot of tau
demo_trace_joint <- ggplot(joint_gibbs_tr %>%
                            filter(str_detect(parameter, "tau_sq|lambda_alpha"))) +
  geom_line(aes(x = iter, y = value)) +
  facet_wrap(~interaction(draw_cat, parameter),
             ncol = 2, scales = "free") +
  theme_minimal() +
  labs(title = "Subject-Level Variance Traces",
       x = "Iteration", y = "Value")

ggsave("../results/2026 ENAR Figures/joint_basis_trace.png",
       basis_trace_joint,
       height = 6, width = 6, units = "in")

ggsave("../results/2026 ENAR Figures/joint_demo_trace.png",
       demo_trace_joint,
       height = 6, width = 6, units = "in")

```

```{r}
#| label: acf-plots

sigma_acf <- acf(cranio_joint$sigma_sq[1,], plot = F)

tau_acf <- acf(cranio_joint$tau_sq[1,], plot = F)

lambda_alpha_acf <- acf(cranio_joint$lambda_demo[1,], plot = F)

acf_df <- bind_rows(
  with(sigma_acf, data.frame(lag, acf)) %>% mutate(param = "sigma_sq"),
  with(tau_acf, data.frame(lag, acf)) %>% mutate(param = "tau_sq"),
  with(lambda_alpha_acf, data.frame(lag, acf)) %>% mutate(param = "lambda_alpha"),
) %>% 
  mutate(param = factor(param, levels = c("sigma_sq", "tau_sq", "lambda_alpha")))

ci_line <- c(-1, 1) * qnorm((1-0.95)/2) / sqrt(ncol(cranio_joint$sigma_sq))

acf_plot <- ggplot(acf_df, aes(x = lag, y = acf)) +
  geom_hline(aes(yintercept = 0)) +
  geom_segment(aes(xend = lag, yend = 0)) +
  geom_hline(yintercept = ci_line, linetype = 2, color = 'darkblue') +
  facet_wrap(~param, nrow = 1) +
  labs(x = "Lag", y = "ACF")

ggsave("../results/2026 ENAR Figures/acf_example.png",
       acf_plot,
       height = 4, width = 6, units = "in")
```


