---
title: "Investigating Low-Rank Demographic Design Matrix"
format: 
  html:
    toc: true
    toc-depth: 2
    toc-title: Contents
    toc-location: left
    df-print: kable
    theme: sandstone
    highlight: haddock
    code-fold: true
    code-overflow: wrap
    knitr:
      opts_chunk:
        echo: true,
        include: true
        message: false,
        warning: false
        results: markup
        fig.align: center
        fig.height: 5
        fig.width: 7
        R.options:
          scipen: 999
          knitr.kable.NA: ""
editor: source
---

```{r}
#| label: setup
#| include: false

rm(list = ls()); gc()

# Load packages
# if(!require("pacman")) install.packages("pacman")
pacman::p_load(
  
  # Format
  latex2exp, table1, gtsummary, ggridges, forestplot,
  broom.helpers, broom.mixed, patchwork, colorRamps,
  
  # Modeling
  mgcv,
  
  # Useful extensions
  gtools, corrplot, MASS, car, Matrix, mvtnorm,
  
  # Basics
  DescTools, tidyverse, magrittr, janitor, glue, skimr,
  knitr, kableExtra, ggpubr, ggpmisc,
)

source(here::here("source", "lm_penalized_gibbs_fn.R"))
source(here::here("source", "construct_smooth_ref_code_fns.R"))
source(here::here("source", "hierarchical_penalized_gibbs_fn.R"))

library(DevCranio)
```

# Data Subset Investigation

## Create data subset

```{r}
#| label: subset-data

cranio_sub <- readRDS(here::here("analysis", "intermediate",
                                 "demographics_filtered.rds"))

cranio_dup_fnames <- readRDS(here::here("analysis", "intermediate",
                                        "duplicate_fnames.rds"))

# Identify patients of each fusion type
set.seed(978)

cranio_demo_test_df <- cranio_sub %>%
  filter(!fname %in% cranio_dup_fnames) %>%
  group_by(fusion_type) %>%
  slice_sample(n = 10)
```

## Create design matrix from subset

```{r}
#| label: setup-subset-model-ingredients

# Convert demographic data to model matrix

cranio_knots_age <- 10

cranio_demo_smooth_test <- smooth.construct2(
  s(age, bs = "cr", k = cranio_knots_age),
  data = cranio_demo_test_df, knots = NULL
)

# Attach name of the dataset to this smooth
attr(cranio_demo_smooth_test, "data") <- "cranio_demo_test_df"

# Use function to reference-code smooth by fusion type
demo_ingredients_test <- setup_reference_model(
  sm = cranio_demo_smooth_test,
  by_var = "fusion_type", param_formula = ~sex
)

# Combine suture fusion penalties so we estimate the same lambda
demo_penalty_list_test <- list(demo_ingredients_test$S[[1]],
                               Reduce("+", demo_ingredients_test$S[-1]))


```

## Analyze subset design matrix

```{r}
#| label: subset-design-analysis

# Summarize dimensions and rank
tibble(
  "nrow" = nrow(demo_ingredients_test$X),
  "ncol" = ncol(demo_ingredients_test$X),
  "rank" = qr(demo_ingredients_test$X)$rank
)

# Plot basis functions
plot_basis_subset <- demo_ingredients_test$X[, 3:11] %>% 
  as.data.frame() %>% 
  rownames_to_column("row") %>% 
  bind_cols(age = cranio_demo_test_df$age) %>%  
  pivot_longer(-c(row, age)) %>% 
  mutate(name = as.numeric(str_remove(name, "V"))) %>%  
  ggplot(aes(x = age, y = value, color = as.factor(name))) + 
  geom_line()

plot_basis_subset

# Plot correlation plots
corrplot(cor(demo_ingredients_test$X[, 3:11]), na.label = "-",
         title = "Normative columns")

corrplot(cor(demo_ingredients_test$X[, 12:20]), na.label = "-",
         title = "Sagittal columns")

corrplot(cor(demo_ingredients_test$X[, 21:29]), na.label = "-",
         title = "Metopic columns")

corrplot(cor(demo_ingredients_test$X[, 30:38]), na.label = "-",
         title = "Right Coronal columns")

corrplot(cor(demo_ingredients_test$X[, 39:47]), na.label = "-",
         title = "Bicoronal columns")

corrplot(cor(demo_ingredients_test$X[, 48:56]), na.label = "-",
         title = "Left Coronal columns")
```

# Full Data and Working Model

```{r}
#| label: full-data

### Full data of frequentist coefficients

# Load intermediate file of design matrix and penalty fed into Bayesian model

## Load all coefficients previously fit, along with demographics
gcv_coeffs <- read_csv(here::here("analysis", "intermediate", "individual_soap_coeffs.csv"))

cranio_coeff_df <- gcv_coeffs %>%
  mutate(fusion_type = fct_infreq(fusion_type),
         sex = factor(sex, levels = c(0,1)))

```

```{r}
#| label: recreate-full-demo-matrix

### Recreate full demographic design matrix

# Construct smooth without constraint or factor levels
cranio_coeff_smooth <- smooth.construct2(
  s(age, bs = "cr", k = cranio_knots_age),
  data = cranio_coeff_df, knots = NULL
)

# Attach name of the dataset to this smooth
attr(cranio_coeff_smooth, "data") <- "cranio_coeff_df"

## Create design and penalty matrices using functions we wrote
coeff_ingredients <- setup_reference_model(
  sm = cranio_coeff_smooth,
  by_var = "fusion_type", param_formula = ~sex
)

# Combine suture fusion penalties so we estimate the same lambda
coeff_S_combo <- list(coeff_ingredients$S[[1]],
                      Reduce("+", coeff_ingredients$S[-1]))
```

```{r}
#| label: analyze-full-data

# Summarize dimensions and rank
tibble(
  "nrow" = nrow(coeff_ingredients$X),
  "ncol" = ncol(coeff_ingredients$X),
  "rank" = qr(coeff_ingredients$X)$rank
)

# Plot basis functions
plot_basis_full <- coeff_ingredients$X[, 3:11] %>% 
  as.data.frame() %>% 
  rownames_to_column("row") %>% 
  bind_cols(age = cranio_coeff_df$age) %>%  
  pivot_longer(-c(row, age)) %>% 
  mutate(name = as.numeric(str_remove(name, "V"))) %>%  
  ggplot(aes(x = age, y = value, color = as.factor(name))) + 
  geom_line()

plot_basis_full

corrplot(cor(coeff_ingredients$X), na.label = "-",
         title = "Full Data")

```


```{r}
#| label: full-demo-model-setup

coeff_y <- cranio_coeff_df$beta_38

# Set default parameters
def_pars_coeff <- c(
  "beta" = 0.0,
  "sigma_sq" = var(coeff_y),
  "lambda" = 0.1,
  "a" = 1.0,
  "b" = 1.0,
  "c" = 1.0,
  "d" = 1.0
)

# Set iterations
bayes_coeff_iters <- 5e3

set.seed(700)

# Run function
coeff_bayes1 <- lm_penalized_gibbs(
  y = coeff_y, X = coeff_ingredients$X,
  S = coeff_S_combo, has_unpenalized = TRUE,
  beta0 = def_pars_coeff["beta"],
  sigmasq0 = def_pars_coeff["sigma_sq"],
  lambda0 = def_pars_coeff["lambda"],
  a_pri = def_pars_coeff["a"],
  b_pri = def_pars_coeff["b"],
  c_pri = def_pars_coeff["c"],
  d_pri = def_pars_coeff["d"],
  iters = bayes_coeff_iters,
  burn_pct = 0.1
)
```

```{r}
#| label: subset-demo-model-setup

# Merge GCV coefficients onto subset data
cranio_demo_test_df_coef <- cranio_demo_test_df %>% 
  left_join(gcv_coeffs %>% select(fname, matches("beta")))

coeff_test_y <- cranio_demo_test_df_coef$beta_38

# Run similar model on subset of data
coeff_bayes_subset <- lm_penalized_gibbs(
  y = coeff_test_y, X = demo_ingredients_test$X,
  S = demo_penalty_list_test, has_unpenalized = TRUE,
  beta0 = def_pars_coeff["beta"],
  sigmasq0 = def_pars_coeff["sigma_sq"],
  lambda0 = def_pars_coeff["lambda"],
  a_pri = def_pars_coeff["a"],
  b_pri = def_pars_coeff["b"],
  c_pri = def_pars_coeff["c"],
  d_pri = def_pars_coeff["d"],
  iters = bayes_coeff_iters,
  burn_pct = 0.1
)
```

```{r}
#| label: subset-gam-model

lambda_direct <- 0.01

subset_direct_mx1 <- solve(
  crossprod(demo_ingredients_test$X) + 
    lambda_direct *  demo_penalty_list_test[[2]])
```


```{r}
#| label: subset-trace-plots

coeff_bayes_sub_tr <- imap(
  coeff_bayes_subset %>%
    list_modify("timing" = zap(),
                "start-stop" = zap()),
  function(x, xn){
    x <- as_tibble(x)
    if(ncol(x) == 1){
      names(x) <- xn
    } else {
      names(x) <- paste0(xn, ".", 1:ncol(x))
    }
    x %<>%
      mutate(iter = 1:n(), .before = everything()) %>%
      pivot_longer(-iter,
                   names_pattern = "(burn_)?(.*)",
                   names_to = c("draw", "name"))

    x
  }
) %>%
  unname() %>%
  list_rbind() %>%
  mutate(draw_cat = if_else(draw == "burn_",
                            "Burn-In", "Posterior"),
         param_num = as.numeric(str_extract(name, "[0-9]+"))) %>%
  mutate(param_num = coalesce(param_num, 1))

# Add default parameters to this table
trace_coeff_subset <- coeff_bayes_sub_tr %>%
  filter(draw_cat == "Burn-In") %>%
  distinct(draw_cat, name, param_num) %>%
  mutate(
    iter = 0,
    value = case_when(
      str_detect(name, "sigma_sq") ~ def_pars_coeff["sigma_sq"],
      str_detect(name, "lambda") ~ def_pars_coeff["lambda"],
      str_detect(name, "beta") ~ def_pars_coeff["beta"],
      T ~ NA
    ))

coeff_bayes_sub_tr %<>% bind_rows(trace_coeff_subset)

# Trace plot of sigma
sigma_trace_subset <- ggplot(coeff_bayes_sub_tr %>%
                              filter(str_detect(name, "sigma_sq"))) +
  geom_line(aes(x = iter, y = value)) +
  facet_grid(rows = name ~ draw_cat, scales = "free") +
  labs(title = "Sigma Squared Trace")

# Trace plot of lambdas
lambda_trace_subset <- ggplot(coeff_bayes_sub_tr %>%
                               filter(str_detect(name, "lambda"))) +
  geom_line(aes(x = iter, y = value), alpha = 0.5) +
  facet_grid(param_num ~ draw_cat, scales = "free") +
  labs(title = "Lambda Trace")

# Trace plot of betas
beta_trace_subset <- ggplot(coeff_bayes_sub_tr %>%
                             filter(str_detect(name, "beta"))) +
  geom_line(aes(x = iter, y = value), alpha = 0.5) +
  facet_grid(param_num ~ draw_cat, scales = "free") +
  labs(title = "Beta Trace")
```

